### ISSUE TITLE
Rotate every arc of pie chart 180 (like sun) with D3 JS. How to calculate translate parameters.

### ISSUE THREAD

**Issue by upans** [enjalot/wwsd#19]
Hi, I am working on pie chart with d3 js. I want to rotate every arc of my pie chart 180. I know that I am unable to explain completely show here is my fiddle link [https://jsfiddle.net/dsLonquL/](https://jsfiddle.net/dsLonquL/). How can i get dynamic parameters for translate() function.

**Comment by enjalot** [comment]
Please ask questions like these on stackoverflow with the d3js tag or on the d3.js slack community. This has nothing to do with mapping or spatial data...

**Comment by upans** [comment]
Thanks enjalot
